### ISSUE TITLE
Cloudinary

### ISSUE THREAD

**Issue by sirrobot01** [Jimlah/hngi7task2Python#1]
You are to work on cloudinary.

https://pypi.org/project/cloudinary/

Read more on it here

### Todo

Writes a function that takes at least three args;

image file
width
height
~~~
cloudinary.utils.cloudinary_url("sample.jpg",
                                width = 100,
                                height = 150,
                                crop = "fill")
~~~

That is how you upload an image. Read more the link above
Your Task

0. Register on cloudinary(It's free), Get an API Key
1. Install cloudinary(python) on your machine(Guide over there)
2. Test upload image to cloudinary
2. Implement it inside the resizer.py and push

**Comment by AdetunjiTejumade** [comment]
#7
